myservers:
  hosts:
    server1:
      ansible_host: 192.168.20.230
      ansible_port: 22
      ansible_ssh_user: ansible
      http_host: uclient.localdomain
      http_conf: uclient.localdomain.conf
    server2: 
      ansible_host: 192.168.20.236
      ansible_port: 22
      ansible_ssh_user: ansible
      http_host: client1.localdomain
      http_conf: client1.localdomain.conf

  vars:
    http_port: "80"

